# Site settings

title: JunjSix Blog

SEOTitle: 小啵儿的小站 | JunjSix Blog

header-img: img/post-bg-universe.jpg

email: JunjSix@outlook.com 

description: "Aloha~这里是小啵老师,你能在这里发现关于我的任何东西."

keyword: "Blog, JunjSix Blog, 小啵儿的博客, JunjSix, 谢俊杰, 混音, 插件, pro tools"

url: "http://1090295493.github.io"          # your host, for absolute URL

baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'

github_repo: "" # you code repository
    <p></p>
    
    <h5>最新文章：</h5>

    <ul>



# Sidebar settings

sidebar: true                           # whether or not using Sidebar.

sidebar-about-description: "只是一个没有故事的南方男孩子"

sidebar-avatar: /img/about-BY-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`







# SNS settings

RSS: true

weibo_username:     p/1005055976793790/home?from=page_100505&mod=TAB&is_all=1#place

zhihu_username:     junjsix

#github_username:    JunjSix

#facebook_username:  暂无

#jianshu_username:   暂无

#twitter_username:   暂无









# Build settings

# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.

permalink: pretty

paginate: 1

exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`







# Gems

# from PR#40, to support local preview for Jekyll 3.0

gems: [jekyll-paginate]









# Markdown settings

# replace redcarpet to kramdown,

# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown

# document: http://jekyllrb.com/docs/configuration/#kramdown

markdown: kramdown

highlighter: rouge

kramdown:

  input: GFM                            # use Github Flavored Markdown !important





# 评论系统

# Disqus（https://disqus.com/）

# disqus_username: qiubaiying



# Gitalk

gitalk:

  enable: false    #是否开启Gitalk评论

  clientID: f2c84e7629bb1446c1a4                            #生成的clientID

  clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #生成的clientSecret

  repo: 1090295493.github.io    #仓库名称

  owner: 1090295493    #github用户名

  admin: 1090295493

  distractionFreeMode: true #是否启用类似FB的阴影遮罩





# Featured Tags

featured-tags: true                     # 是否使用首页标签

featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页







# Progressive Web Apps

chrome-tab-theme-color: "#000000"

service-worker: true

